-- Add migration script here
DROP TABLE "user";
DROP TABLE task;
CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username varchar(128) NOT NULL UNIQUE,
    pwd varchar(256),
    pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
    salt_token uuid NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title varchar(256) NOT NULL
);

INSERT INTO "user" (username) VALUES ('demo1');